name: Swift Package

on: [push, pull_request]

jobs:
  spm:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: SPM Build
      run: swift build
    - name: SPM Test
      run: swift test

  xcode:
    runs-on: macos-13
    name: "Xcode - ${{ matrix.platform }}"
    strategy:
      matrix:
        include:
        - platform: macOS
        - platform: iOS
        - platform: tvOS
        - platform: watchOS
    steps:
    - uses: actions/checkout@v4
    - name: "${{ matrix.platform }} Build"
      run: |
        set -o pipefail
        xcodebuild build -scheme B9AssociatedObject -destination "generic/platform=${{ matrix.platform }}" | xcbeautify
